"""Landmark world for the synthetic stereo front end.

Why a landmark world and not images
-----------------------------------
carcajou's entire claim to being believable is the identity in
``datasets/synthetic.py``: truth is generated by inverting the mechanization,
so a noise-free run reproduces it to machine precision and every metre of drift
is traceable to an error someone deliberately injected.

Rendering photorealistic stereo pairs would break that chain. A learned feature
detector's failure modes are not parameterised, so a drift number produced
through one is not attributable. Projecting a known 3D point set through a
known camera model keeps the chain intact: with zero pixel noise the front end
recovers the true relative pose exactly (``test_vision.py``), and every metre of
VO-induced drift is attributable to pixel noise, geometry, or the dynamic-object
contamination that Phase 1 exists to measure.

What is deliberately *not* modelled: illumination, texture, occlusion,
descriptor aliasing, rolling shutter. Those are front-end quality effects. They
are absorbed into the pixel-noise and outlier-rate parameters, which is an
approximation, and it is stated here rather than buried.

Two populations of landmark
---------------------------
**Static** points form a corridor along the route: facades, poles, kerbs, road
markings. They are fixed in the nav frame.

**Dynamic** points ride a lead vehicle travelling the same route a few car
lengths ahead. This is the adversarial case on purpose. A lead car holding
station at roughly ego speed is nearly *stationary in the ego frame*, so its
features vote for zero ego motion. RANSAC does not save you: once the lead
vehicle owns enough of the image, the moving points are the consensus set and
the static world becomes the outlier. That is the failure Phase 1 measures.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from ..datasets.synthetic import Trajectory


@dataclass
class LandmarkWorld:
    """Static landmarks in the nav frame plus a dynamic-actor generator.

    Attributes
    ----------
    p_static : ``(M,3)`` NED positions of fixed structure
    actor_body : ``(K,3)`` offsets of the lead vehicle's points in its own
        body frame, so the cluster rotates and translates rigidly with it
    """

    p_static: np.ndarray
    actor_body: np.ndarray
    traj: Trajectory
    gap_m: float = 12.0
    lateral_offset: float = 0.0

    # ------------------------------------------------------------- dynamics
    def actor_pose(self, k: int) -> tuple[np.ndarray, np.ndarray] | None:
        """Pose of the lead vehicle at trajectory index ``k``.

        The lead vehicle is the ego vehicle's own future: it occupies the pose
        the ego will reach after ``gap_m`` of arc length. That makes it follow
        the road exactly, brake at the same lights, and hold station at ego
        speed, which is precisely the geometry that defeats an unmasked VO.
        """
        s = self._arc
        target = s[k] + self.gap_m
        if target > s[-1]:
            return None
        j = int(np.searchsorted(s, target))
        j = min(j, len(s) - 1)
        R = self.traj.R[j]
        p = self.traj.p[j] + R @ np.array([0.0, self.lateral_offset, 0.0])
        return R, p

    def actor_points(self, k: int) -> np.ndarray:
        """Dynamic landmark positions in the nav frame at index ``k``."""
        pose = self.actor_pose(k)
        if pose is None or len(self.actor_body) == 0:
            return np.zeros((0, 3))
        R, p = pose
        return (R @ self.actor_body.T).T + p

    @property
    def _arc(self) -> np.ndarray:
        if not hasattr(self, "_arc_cache"):
            object.__setattr__(self, "_arc_cache", self.traj.arc_length())
        return self._arc_cache


def make_world(
    traj: Trajectory,
    rng: np.random.Generator,
    spacing_m: float = 1.5,
    per_station: int = 6,
    lateral_range: tuple[float, float] = (2.5, 18.0),
    height_range: tuple[float, float] = (-9.0, 0.3),
    n_actor_points: int = 240,
    actor_size: tuple[float, float, float] = (4.6, 1.9, 1.6),
    gap_m: float = 12.0,
) -> LandmarkWorld:
    """Build a corridor of static structure plus one lead-vehicle point cluster.

    ``per_station`` points are spawned every ``spacing_m`` of arc length, split
    between the two sides of the road, at heights spanning the road surface to
    roof level. Density is chosen so a typical frame holds a few hundred
    trackable points, which is what a real stereo front end returns after
    ratio-test and left-right consistency rejection.
    """
    arc = traj.arc_length()
    stations = np.arange(0.0, arc[-1], spacing_m)
    idx = np.searchsorted(arc, stations)
    idx = np.clip(idx, 0, len(arc) - 1)

    n = len(idx) * per_station
    side = rng.choice([-1.0, 1.0], size=n)
    lateral = side * rng.uniform(*lateral_range, size=n)
    down = rng.uniform(*height_range, size=n)
    along = rng.uniform(-spacing_m / 2, spacing_m / 2, size=n)

    R_at = traj.R[np.repeat(idx, per_station)]
    p_at = traj.p[np.repeat(idx, per_station)]
    offs = np.stack([along, lateral, down], axis=1)
    p_static = p_at + np.einsum("nij,nj->ni", R_at, offs)

    # Lead vehicle: a shell of points on a box, not a solid, since a stereo
    # front end only ever sees the surface facing it.
    L, W, H = actor_size
    u = rng.uniform(-0.5, 0.5, size=(n_actor_points, 3)) * np.array([L, W, H])
    face = rng.integers(0, 3, size=n_actor_points)
    u[face == 0, 0] = -L / 2  # rear face, the one the ego actually sees
    u[face == 1, 1] = np.sign(u[face == 1, 1]) * W / 2
    u[face == 2, 2] = -H / 2
    # Actor body frame is FRD like the ego; its origin sits at road height.
    actor_body = u + np.array([0.0, 0.0, -H / 2])

    return LandmarkWorld(
        p_static=p_static, actor_body=actor_body, traj=traj, gap_m=gap_m
    )
